import './globals.css';
import './aos.css';
import { LanguageProvider } from '@/context/Language';
import { MenuProvider } from '@/context/MenuContext';
import Head from 'next/head';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "WebToon Koi Content",
  description: "Generated by create next app",
  icons: {
    icon: "/images/title_logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useEffect(() => {
  //   const elements = document.querySelectorAll('body *');
  //   elements.forEach((element) => {
  //     // 텍스트 컨텐츠에서 HTML 주석과 공백 문자를 제거
  //     const textContent = (element.textContent?.replace(/<!--.*?-->/g, '').trim()) || '';
  //     if (/^[\x00-\x7F]*$/.test(textContent)) {
  //       element.classList.add('font-english');
  //     } else {
  //       element.classList.add('font-korean');
  //     }
  //   });
  // }, []);

  return (
    <html lang="ko" data-theme="light">
      <Head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Pretendard:wght@400;700&display=swap" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/gh/jgthms/fonts@master/MADETommy/MADETommy.css" rel="stylesheet" />
      </Head>
      <body>
        <LanguageProvider>
          <MenuProvider>{children}</MenuProvider>
        </LanguageProvider>
        <script src="https://cdn.jsdelivr.net/npm/tw-elements@1.0.0/dist/js/tw-elements.umd.min.js" async></script>
        <script src="https://unpkg.com/aos@next/dist/aos.js" async></script>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" async></script>
      </body>
    </html>
  );
}
